# Generated by Django 3.2.9 on 2022-02-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits_managerAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitfulfillment',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
