# Generated by Django 3.2.9 on 2022-02-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_managerAPI', '0004_alter_habitfulfillment_fulfillment_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitfulfillment',
            name='fulfillment_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits_managerAPI.fulfillmentlevel'),
        ),
        migrations.AlterField(
            model_name='habitfulfillment',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillemnts', to='habits_managerAPI.habit'),
        ),
    ]
