# Generated by Django 3.2.9 on 2022-02-27 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits_managerAPI', '0006_habit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits_managerAPI.habitfulfillment')),
            ],
        ),
    ]
